version: "3"

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bookr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  asynq:
    image: hibiken/asynqmon
    command:
      - --redis-addr=redis:6379
      - --enable-metrics-exporter
    ports:
      - 8080:8080
